const data =[
    {
        id:1,
        img:'./Menu/menuimg.jpg',
        price:2980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:2,
        bathroom:2,
        area:1000,

    },
    {
        id:2,
        img:'./Menu/menuimg.jpg',
        price:3980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:4,
        bathroom:8,
        area:2000,
    },
    {
        id:2,
        img:'./Menu/menuimg.jpg',
        price:3980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:4,
        bathroom:8,
        area:3000,
    },
    {
        id:2,
        img:'./Menu/menuimg.jpg',
        price:3980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:4,
        bathroom:8,
        area:2000,
    },
    {
        id:2,
        img:'./Menu/menuimg.jpg',
        price:3980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:4,
        bathroom:8,
        area:4000,
    },
    {
        id:2,
        img:'./Menu/menuimg.jpg',
        price:3980,
        name:'Pal horbour',
        address:'2699 green valley valley valley',
        beds:4,
        bathroom:8,
        area:5000,
    },
]

export default data